
default:
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_true.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_let.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_and.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_and2.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_and3.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_and4.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_implies.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_implies2.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_implies3.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_implies4.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_or.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/theorem_or.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/rec1.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/all1.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/all2.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/all3.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/fun1.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/inst1.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/bintree.pf
	/opt/homebrew/bin/python3.10 ./parser.py test/induction1.pf

# TODO

